osx_image: xcode11
language: objective-c
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
notifications:
  email:
    - jam330257@gmail.com

# Ensure that fastlane is at the latest version
before_install:
- brew update
- bundle install
- bundle exec pod install

jobs:
  include:
    - stage: test
      script: 
        - bundle exec fastlane test